### ISSUE TITLE
Search linking to raw inputs not rendered page

### ISSUE THREAD

**Issue by willp-bl** [alphagov/tech-docs-gem#59] opened 2018-11-23 10:36 UTC
[The GDS Way](https://gds-way.cloudapps.digital/) has just migrated to multi page view but search is not working.  

When you use search the links are following the path of the raw markdown files and not the pages that are rendered and displayed.

**Comment by bahmady** [comment] 2018-11-23 11:20
If I understand the problem correctly this is (unfortunately) expected behaviour. 

For example: if I search "Secure a service" at https://gds-way.cloudapps.digital/ then it comes up with 17 results including "Secure your service", which doesn't match the title it links to at https://gds-way.cloudapps.digital/ (which is "How to secure a service"). 

To fix the specific problem for that specific search failure, I can only suggest changing this file:

`<path>/gds-way/source/secure-services.html.md.erb` 

At the moment in the `title` field it says: "Secure your service". That's where the search is getting it from. 

Obviously the same "fix" would need to be applied across the whole thing.

**Comment by tijmenb** [comment] 2019-02-13 09:08
This issue seems to be fixed on GDS Way. Feel free to reopen if that's not the case.

**Closed by tijmenb** 2019-02-13 09:08 UTC
